### ISSUE TITLE
Error: missing return in a function expected to return 'String?'

### ISSUE THREAD

**Issue by iMuFeng** [sindresorhus/dark-mode#18]
Build with macOS Mojave 10.14.6 on MBP 2017

```
Last 15 lines from /Users/mufeng/Library/Logs/Homebrew/dark-mode/01.build:
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~
/tmp/dark-mode-20191209-84518-17xuhso/dark-mode-3.0.0/Sources/DarkMode.swift:9:3: error: missing return in a function expected to return 'Bool'
                }
                ^
/tmp/dark-mode-20191209-84518-17xuhso/dark-mode-3.0.0/Sources/util.swift:6:1: error: missing return in a function expected to return 'String?'
}
```

**Comment by sindresorhus** [comment]
You need to compile with the latest Xcode (11.2).
